version: '3.8'

services:
  rust:
    build:
      context: ./rust
      dockerfile: Dockerfile
    image: practice-rust:latest
    volumes:
      - ./rust:/usr/src/rust
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true